### PR TITLE
Extension of the support for further encodings according to the specification ETSI EN 300 468

### PR DESCRIPTION
**Pull request by pjsharp**
Changes:

* encodings iso-8859-[1..4] and freesat huffman are now also supported
* fix for incorrect parsing and encoding/decoding of some event items
* repetitive calls have been encapsulated into the methods

### CODE REVIEW

**Comment by dazulrich** [comment]
I tried your changes because I regularly have garbage chars at the end of the desciption (recording on 28.2E) and not sure whether its OATV putting them wrong into the EIT file or whether EMC is parsing it wrong.

attached EIT shows 2 garbage chars at the end of description using the current version of EMC.
Clip show of dramatic confrontations narrated by George Lamb. (S4 Ep3)**ñP**

with your PR those are no longer displayed.. 

But I can't properly test as it is crashing EMC on a lot of recordings.

```
00:33:48.2547   File "/usr/lib/enigma2/python/Plugins/Extensions/EnhancedMovieCenter/EitSupport.py", line 455, in __readEitFile
00:33:48.2577     short_event_descriptor = "".join(short_event_descriptors[0])
00:33:48.2595                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:33:48.2599 TypeError: sequence item 0: expected str instance, bytes found
```
example file that is "fixed"
[5ACTION - Fights, Camera, Action.eit.fixed_char.txt](https://github.com/oe-mirrors/e2openplugin-EnhancedMovieCenter/files/10145397/5ACTION.-.Fights.Camera.Action.eit.fixed_char.txt)

example file that crashes.
[5 USA - Criminal Minds.eit.crash.txt](https://github.com/oe-mirrors/e2openplugin-EnhancedMovieCenter/files/10145398/5.USA.-.Criminal.Minds.eit.crash.txt)

**Comment by pjsharp** [comment]
Thank you for the interesting example. I fixed the cause of the crash.
However, the file contains an encoding (Huffman) which is not (yet) supported by EitSupport.py, so the event information in the EMC will still not be displayed correctly.
Maybe in a future version.

**Comment by dazulrich** [comment]
No problem . I have a bunch more that seemingly contain garbage in the short_event_descriptor. Looks Like EMC shows the clean description from the meta file and appends the garbage. I happens for timer or instant recordings with oatv 7.1 and 7.2.. I'll post one or two samples later. Maybe you can confirm that they all have same issue.

edit: added 3 files with garbage description.
[20221115 1447 - Sony Movies - Cradle Swapping.eit.txt](https://github.com/oe-mirrors/e2openplugin-EnhancedMovieCenter/files/10146180/20221115.1447.-.Sony.Movies.-.Cradle.Swapping.eit.txt)
[20221123 1352 - ITV1 HD - FIFA World Cup 2022_ Germany v Japan.eit.txt](https://github.com/oe-mirrors/e2openplugin-EnhancedMovieCenter/files/10146181/20221123.1352.-.ITV1.HD.-.FIFA.World.Cup.2022_.Germany.v.Japan.eit.txt)
[20221109 2257 - 5USA+1 - New_ Criminal Minds.eit.txt](https://github.com/oe-mirrors/e2openplugin-EnhancedMovieCenter/files/10146182/20221109.2257.-.5USA%2B1.-.New_.Criminal.Minds.eit.txt)

Next time i see it, i'll capture the epg.dat. hopefully someone can check whether the data is corrupted inside the epg or is corrupted when creating the eit file. (happy do build here and debug , but would need some pointers as to what what to look for)
edit2: did a few instant recordings and just got another one.. saved the epg.dat and the description in the EPG file matches the special characters stored in the EIT file. which means either the epgcache code is messing it up when parsing/storing it. 
Or the data came in like that and it is simply uses/ store as is. 

`IpõÙ¾'Fq®‚«ÝÓŒÂ$}ÿ7ÊžkÎ»/}%÷šöÝÿh$¸{ª†ß0ú€Û˜]`
instead of 
`Santa on Cakecation: The baking teams are challenged to create cakes that depict Santa on his dream holiday. The judges must decide which masterpiece takes them on a tasty trip. S1 Ep6`

[20221203 1444 - ITVBe - The Big Bake_ Holiday.eit.txt](https://github.com/oe-mirrors/e2openplugin-EnhancedMovieCenter/files/10146808/20221203.1444.-.ITVBe.-.The.Big.Bake_.Holiday.eit.txt)

after deleting epg.dat, and collecting new EPG data, the next instant recoding worked as expected and the EPG.dat contains the expected string. 
maybe EPG data is corrupted at times.. but may that is better raised on OATV repo and not here.

**Comment by pjsharp** [comment]
I examined the files and in all cases the reason is due to the special encoding. This was also not supported by the current version.

But it no longer causes a crash of EMC, right?

The content of these files is correct, a part (event name) is encoded in utf-8 and can therefore be displayed correctly, another part (short-event-description) is encoded with an encoding not supported by EMC.  Due to the encoding, it may be visually unreadable for us when looking at the files.

On which transponders are these channels?

**Comment by dazulrich** [comment]
Sorry , yes it's not crashing anymore. Thanks.
Some of the transponders on 28.2E
10906V itvbe
11307V sony movies
11068V itv1hd
But can happen on others too.

**Comment by pjsharp** [comment]
Yes, of course. As long as the huffman encoding is not supported by the EMC plugin, it can be the case with any transmitter that encodes the data in this way.

But this issue is not new now, it has always been like this.

**Comment by pjsharp** [comment]
I've now implemented the support for the freesat huffman coding. Could you provide me a few more examples, I would like to use them for testing. Gladly zipped as a whole. Many thanks in advance!

**Comment by dazulrich** [comment]
Hi. Sorry was away for few days.  Will have a look what files I can gather. What I don't understand is that when I do 1min test recordings to trigger this, a second recording of same channel a minute later the eit file contains the readable  description.

**Comment by pjsharp** [comment]
Thanks. No, it is not possible that the description in this case comes from the eit file. This can only come from a (live) EPG or somewhere else, because EMC has not supported this encoding so far. Or you are using also another plugin to browse the recordings.

**Comment by dazulrich** [comment]
You misunderstood. 
Oatv recording creates the eit file.
Recording parts of same program back to back and even if the first recording creates an eit file with huffmann encoded short description, the 2nd recording contains description in clear text.
I get the emc only displays what's in the eit file.

**Comment by pjsharp** [comment]
Support for freesat huffman encoding added

**Comment by dazulrich** [comment]
hi, looks good. 
when renaming the meta files I get the same short desciption displayed as it is stored in the meta file.
Previously it only showed the garbage chars...

**Comment by pjsharp** [comment]
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/issues/289

**Comment by jbleyel** [comment]
Hi @pjsharp ,

Nice work but this branch is python 3 only.
You do not need to support python2.

**Comment by pjsharp** [comment]
Hi @jbleyel,

thanks! I know it's python3 branch, but the previous version still had python2 support, so I kept it and of course tested it for both.

**Comment by jbleyel** [comment]
I have one last question.
Why don’t you use the eit parser from enigma2?
The whole eit support code can go.

**Comment by pjsharp** [comment]
The EMC plugin has always used the parser from EitSupport. I haven't changed that, although I've asked myself why E2's EIT processing isn't being used. I figured there must be important reasons why it's not done that way. And I didn't dare to make such a "radical" change without prior consultation. Then I extended the existing parser only with the points that I was missing and corrected what was wrong.

In the next step I can try to switch the EMC to E2 parser if desired.

**Comment by pjsharp** [comment]
@jbleyel https://github.com/oe-mirrors/e2openplugin-EnhancedMovieCenter/pull/8

**Pull request merged**
