### PR TITLE
Event Infos e2based

### PR DESCRIPTION
**Pull request by pjsharp**
Changes:

- EIT from enigma (EitSupport.py not needed anymore)
- META from enigma (MetaSupport.py not needed anymore)
- some global variables and methods moved to CommonSupport.py (to avoid cross import references)
- ServiceSupport.py refactored

### CODE REVIEW

**Comment by jbleyel** [comment]
i hope you have tested all your changes because you have removed a lot of things.

**Comment by pjsharp** [comment]
@jbleyel  Yes, of course. I tested everything for a few days as far as I could. Even with the greatest care, it cannot be ruled out that a hidden error can still occur under a certain configuration combination. If anything comes up, I'll fix it immediately.

**Comment by jbleyel** [comment]
> @jbleyel Yes, of course. I tested everything for a few days as far as I could. Even with the greatest care, it cannot be ruled out that a hidden error can still occur under a certain configuration combination. If anything comes up, I'll fix it immediately.

Good work .. by the way.

**Comment by jbleyel** [comment]
You can also take a look here -> 
https://github.com/betonme/e2openplugin-EnhancedMovieCenter/issues
And check the last 4 issues.

They may also affects our fork.

**Comment by pjsharp** [comment]
Ok, I'll take a loook.

**Comment by pjsharp** [comment]
@jbleyel  Hi! Someone (repository owner) has just locked the conversation for 2 of the above-mentioned issues and deleted my last posting. I don't understand if he has problem with that if the issues could be fixed.

**Comment by jbleyel** [comment]
Okay. Let me check.

**Comment by jbleyel** [comment]
New Repro -> https://github.com/oe-mirrors/EnhancedMovieCenter
This new repro is not used for image build until we have refactored some things.
But you can use this new code for testing on your box.

We will switch to this new repro after refactor is finished.

**Comment by pjsharp** [comment]
Thanks for the info.

**Pull request merged**
